# Generated by Django 5.2.5 on 2026-09-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_campaign_status_creditlog_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='call_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='visit_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
